#name: Deploy to CloudFront

#on:
  #push:
    #branches:
     # - main

#jobs:
  #deploy:
    #runs-on: ubuntu-latest

    #steps:
    #- name: Checkout code
    #  uses: actions/checkout@v2

    #- name: Install AWS CLI
    #  run: |
       # sudo apt-get update
        #sudo apt-get install -y awscli

    #- name: Deploy to CloudFront
     # run: |
       # aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
       # aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       # aws configure set region ${{ secrets.AWS_REGION }}

        #aws s3 sync . s3://www.sethblvck.com

        #aws s3api put-object-acl --bucket www.sethblvck.com --acl public-read --recursive

       # aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
name: Deploy to CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Deploy to CloudFront
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 sync . s3://www.sethblvck.com
        aws s3api put-object-acl --bucket www.sethblvck.com --acl public-read --recursive
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'